default:
	g++ test_utils.cpp ../../src/graph.cpp ../../src/operations.cpp ../../src/utils.cpp ../../src/parser.cpp ../../libs/mini-yaml/yaml/Yaml.cpp ../../libs/csv-parser/include/csv.hpp -lgtest -lgtest_main -lpthread -o test_utils.out 
